### ISSUE TITLE
evil-substitute is active in new buffers

### ISSUE THREAD

**Issue by NightMachinery** [hlissner/evil-snipe#58]
evil-substitute is active in buffers with the fundamental major mode, even though I have set the auto-disable to 't. Calling the function evil-snipe-local-mode enables evil-snipe in that buffer.

**Comment by hlissner** [comment]
I've pushed a change to allow evil-snipe to work in fundamental-mode. Please update and let me know.

Also, `evil-snipe-auto-disable-substitute` was removed in the latest version of evil-snipe. It should no longer be necessary.

**Comment by NightMachinary** [comment]
@hlissner The latest MELPA (;; Package-Version: 20180417.1915) is still buggy.

**Comment by hlissner** [comment]
Sorry for the _hugely_ late response, but is this issue still present? I cannot currently reproduce it.
